export interface Driver {
  id: number
  name: string
  team: string
  teamColor: string
  number: number
  points: number
  podiums: number
  wins: number
  fastestLaps: number
  championships: number
  country: string
  imageQuery: string
}

export const drivers: Driver[] = [
  {
    id: 1,
    name: "Lando Norris",
    team: "McLaren",
    teamColor: "from-orange-500 to-blue-600",
    number: 4,
    points: 390,
    podiums: 18,
    wins: 4,
    fastestLaps: 3,
    championships: 1,
    country: "United Kingdom",
    imageQuery: "formula 1 driver Lando Norris headshot",
  },
  {
    id: 2,
    name: "Oscar Piastri",
    team: "McLaren",
    teamColor: "from-orange-500 to-blue-600",
    number: 81,
    points: 366,
    podiums: 12,
    wins: 2,
    fastestLaps: 2,
    championships: 0,
    country: "Australia",
    imageQuery: "formula 1 driver Oscar Piastri headshot",
  },
  {
    id: 3,
    name: "Max Verstappen",
    team: "Red Bull Racing",
    teamColor: "from-blue-900 to-yellow-400",
    number: 1,
    points: 341,
    podiums: 25,
    wins: 9,
    fastestLaps: 8,
    championships: 4,
    country: "Netherlands",
    imageQuery: "formula 1 driver Max Verstappen headshot",
  },
  {
    id: 4,
    name: "George Russell",
    team: "Mercedes",
    teamColor: "from-cyan-400 to-gray-300",
    number: 63,
    points: 276,
    podiums: 8,
    wins: 2,
    fastestLaps: 2,
    championships: 0,
    country: "United Kingdom",
    imageQuery: "formula 1 driver George Russell headshot",
  },
  {
    id: 5,
    name: "Charles Leclerc",
    team: "Ferrari",
    teamColor: "from-red-600 to-red-800",
    number: 16,
    points: 214,
    podiums: 11,
    wins: 3,
    fastestLaps: 5,
    championships: 0,
    country: "Monaco",
    imageQuery: "formula 1 driver Charles Leclerc headshot",
  },
  {
    id: 6,
    name: "Lewis Hamilton",
    team: "Ferrari",
    teamColor: "from-red-600 to-red-800",
    number: 44,
    points: 148,
    podiums: 4,
    wins: 0,
    fastestLaps: 1,
    championships: 7,
    country: "United Kingdom",
    imageQuery: "formula 1 driver Lewis Hamilton headshot",
  },
  {
    id: 7,
    name: "Kimi Antonelli",
    team: "Mercedes",
    teamColor: "from-cyan-400 to-gray-300",
    number: 12,
    points: 122,
    podiums: 3,
    wins: 0,
    fastestLaps: 0,
    championships: 0,
    country: "Italy",
    imageQuery: "formula 1 driver Andrea Kimi Antonelli headshot",
  },
  {
    id: 8,
    name: "Alexander Albon",
    team: "Williams",
    teamColor: "from-blue-500 to-blue-700",
    number: 23,
    points: 73,
    podiums: 2,
    wins: 0,
    fastestLaps: 0,
    championships: 0,
    country: "Thailand",
    imageQuery: "formula 1 driver Alexander Albon headshot",
  },
  {
    id: 9,
    name: "Nico Hülkenberg",
    team: "Sauber",
    teamColor: "from-green-600 to-gray-700",
    number: 27,
    points: 43,
    podiums: 1,
    wins: 0,
    fastestLaps: 1,
    championships: 0,
    country: "Germany",
    imageQuery: "formula 1 driver Nico Hulkenberg headshot",
  },
  {
    id: 10,
    name: "Isack Hadjar",
    team: "Racing Bulls",
    teamColor: "from-blue-600 to-blue-800",
    number: 6,
    points: 43,
    podiums: 1,
    wins: 0,
    fastestLaps: 0,
    championships: 0,
    country: "France",
    imageQuery: "formula 1 driver Isack Hadjar headshot",
  },
  {
    id: 11,
    name: "Sergio Perez",
    team: "Red Bull Racing",
    teamColor: "from-blue-900 to-yellow-400",
    number: 11,
    points: 38,
    podiums: 1,
    wins: 0,
    fastestLaps: 0,
    championships: 0,
    country: "Mexico",
    imageQuery: "formula 1 driver Sergio Perez headshot",
  },
  {
    id: 12,
    name: "Fernando Alonso",
    team: "Aston Martin",
    teamColor: "from-green-500 to-green-700",
    number: 14,
    points: 35,
    podiums: 0,
    wins: 0,
    fastestLaps: 0,
    championships: 2,
    country: "Spain",
    imageQuery: "formula 1 driver Fernando Alonso headshot",
  },
  {
    id: 13,
    name: "Pierre Gasly",
    team: "Alpine",
    teamColor: "from-pink-500 to-blue-600",
    number: 10,
    points: 28,
    podiums: 0,
    wins: 0,
    fastestLaps: 0,
    championships: 0,
    country: "France",
    imageQuery: "formula 1 driver Pierre Gasly headshot",
  },
  {
    id: 14,
    name: "Lance Stroll",
    team: "Aston Martin",
    teamColor: "from-green-500 to-green-700",
    number: 18,
    points: 24,
    podiums: 0,
    wins: 0,
    fastestLaps: 0,
    championships: 0,
    country: "Canada",
    imageQuery: "formula 1 driver Lance Stroll headshot",
  },
  {
    id: 15,
    name: "Jack Doohan",
    team: "Alpine",
    teamColor: "from-pink-500 to-blue-600",
    number: 7,
    points: 17,
    podiums: 0,
    wins: 0,
    fastestLaps: 0,
    championships: 0,
    country: "Australia",
    imageQuery: "formula 1 driver Jack Doohan headshot",
  },
  {
    id: 16,
    name: "Liam Lawson",
    team: "Racing Bulls",
    teamColor: "from-blue-600 to-blue-800",
    number: 30,
    points: 12,
    podiums: 0,
    wins: 0,
    fastestLaps: 0,
    championships: 0,
    country: "New Zealand",
    imageQuery: "formula 1 driver Liam Lawson headshot",
  },
  {
    id: 17,
    name: "Carlos Sainz",
    team: "Williams",
    teamColor: "from-blue-500 to-blue-700",
    number: 55,
    points: 8,
    podiums: 0,
    wins: 0,
    fastestLaps: 0,
    championships: 0,
    country: "Spain",
    imageQuery: "formula 1 driver Carlos Sainz headshot",
  },
  {
    id: 18,
    name: "Gabriel Bortoleto",
    team: "Sauber",
    teamColor: "from-green-600 to-gray-700",
    number: 5,
    points: 6,
    podiums: 0,
    wins: 0,
    fastestLaps: 0,
    championships: 0,
    country: "Brazil",
    imageQuery: "formula 1 driver Gabriel Bortoleto headshot",
  },
  {
    id: 19,
    name: "Esteban Ocon",
    team: "Haas",
    teamColor: "from-gray-400 to-red-600",
    number: 31,
    points: 4,
    podiums: 0,
    wins: 0,
    fastestLaps: 0,
    championships: 0,
    country: "France",
    imageQuery: "formula 1 driver Esteban Ocon headshot",
  },
  {
    id: 20,
    name: "Oliver Bearman",
    team: "Haas",
    teamColor: "from-gray-400 to-red-600",
    number: 87,
    points: 2,
    podiums: 0,
    wins: 0,
    fastestLaps: 0,
    championships: 0,
    country: "United Kingdom",
    imageQuery: "formula 1 driver Oliver Bearman headshot",
  },
]

export const teams = [
  "McLaren",
  "Red Bull Racing",
  "Ferrari",
  "Mercedes",
  "Aston Martin",
  "Alpine",
  "Williams",
  "Racing Bulls",
  "Sauber",
  "Haas",
]
